name: minetest-luk3yx
summary: "luk3yx's unofficial Minetest builds."
description: |
  Minetest is a Minecraft-inspired game written from scratch and licensed
  under the LGPL (version 2.1 or later). It supports both survival and
  creative modes along with multiplayer support, dynamic lighting, and an
  "infinite" map generator.
grade: stable
confinement: strict
icon: snap/gui/minetest.svg
version: stable
version-script: git -C parts/minetest/src describe --tags | cut -d- -f1
base: core18

apps:
  minetest:
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl, pulseaudio]
  minetest-luk3yx:
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl, pulseaudio]

parts:
  launcher:
    source: snap/scripts
    plugin: dump
  minetestgame:
    source: https://github.com/minetest/minetest_game.git
    source-branch: stable-0.4
    plugin: dump
    organize:
      '*': 'share/minetest/games/minetest_game/'
  minetest:
    source: https://github.com/minetest/minetest.git
    source-branch: stable-0.4
    plugin: cmake
    configflags: ["-DRUN_IN_PLACE=FALSE", "-DCMAKE_BUILD_TYPE=Release"]
    build-packages:
      - cmake
      - gcc
      - g++
      - gettext
      - imagemagick
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libirrlicht-dev
      - libjpeg-dev
      - libjsoncpp-dev
      - libleveldb-dev
      - libluajit-5.1-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libpulse-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libx11-dev
      - zlib1g-dev
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - libcurl3-gnutls
      - libgl1-mesa-glx
      - libirrlicht1.8
      - libxshmfence1
      - libxcb-sync1
      - libxcb-present0
      - libxcb-glx0
      - libxcb-dri3-0
      - libxcb-dri2-0
      - libvorbisfile3
      - libsnappy1v5
      - libfreetype6
      - libopenal1
      - libluajit-5.1-2
      - libleveldb1v5
      - libjpeg-turbo8
      - libxxf86vm1
      - libxfixes3
      - libxext6
      - libxdamage1
      - libx11-6
      - libx11-xcb1
